### PR TITLE
v0.2.1-002

### PR DESCRIPTION
**Pull request by benjaminbollen**
Tagging a fresh version of next, previous version 0.2.1-001 is broken on package builds

### CODE REVIEW

**Comment by benjaminbollen** [comment]
Can we tag this commit in MaidSafe with 'v0.2.1-002' ?

**Comment by Fraser999** [comment]
I think you can apply the tag to your fork and it will come over when we merge.  Do you want to try that?

**Comment by benjaminbollen** [comment]
No I looked it up, tags in forks are not transferred with a pull request - at least according to http://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request

**Comment by benjaminbollen** [comment]
Closing and reopening for new v0.2.002 in a minute

**Pull request closed without merging**
