### PR TITLE
Maid 714: Stop Protobuf generating illegal C++

### PR DESCRIPTION
**Pull request by ned14**
Let me know if the SHA stamping of the submodules is a problem.

### CODE REVIEW

**Comment by Fraser999** [comment]
I'd prefer if the SHA stamps were removed if possible please NIall.

**Comment by breese** [comment]
The SHA hashes downs out the code commits, making it difficult to read the git history afterwards. So I also vote for their removal.

**Comment by ned14** [comment]
I'll see if I can flatten the SHA stamping commits in git history. Failing that I'll just cherry pick the fix over to a virgin git clone. BTW after signing a contract Google accepted the fix to protobuf, so that's fixed in head now.

**Comment by ned14** [comment]
Cool, that worked.

**Comment by Fraser999** [comment]
Thanks Niall.

**Pull request merged**
